classes: {
  empty_shell: {
    vertical-gap: 0
    style.fill: transparent
    style.stroke-width: 0
  }
  invisible: {
    style.opacity: 0
    label: a
  }
}

LogHorizontal: "" {
  grid-rows: 1
  grid-columns: 4
  horizontal-gap: 0
  vertical-gap: 0
  a: ""
  b: ""
  c: ""
  d: ""
}

LongBitMap_v2:  {
  a:|`go
  data[] = 
  `|

}

LongBitMap:  {
  label:"int64"
  grid-rows: 1
  grid-gap: 10
  bits: "00100....1001" {
    shape: text
  }
  label.near: outside-top-center
}
Chunck_Compressed: "2^32 bits" {
  grid-columns: 2
  grid-gap: 10
  bits: "00111....1001;" {
    shape: text
  }
  size: "Compressed" {
    shape: text
  }
  label.near: outside-top-center
}
Chunck_Raw: "2^32 bits" {
  grid-columns: 2
  grid-gap: 10
  bits: "00111....1001;" {
    shape: text
  }
  size: "Uncompressed" {
    shape: text
  }
  label.near: outside-top-center
}
