classes: {
  ...@index.classes
}
Condition: "" {
  grid-columns: 1
  grid-rows: 2
  grid-gap: 0
  class: empty_shell
  vertical-gap: 5
  real_time: "" {
    ...@rt_index.RT_INDEX
  }
  batch: "" {
    grid-columns: 3
    grid-gap: 0
    class: empty_shell
    pad1: "sd" {style.opacity: 0; width: 300}
    batch: {
      ...@batch_bitmap.BATCH_INDEX
      width: 400
    }
    pad2: "sd" {style.opacity: 0; width: 300}
  }
  label.near: outside-top-center
}
