classes: {
  ...@index.classes
}
Updates: "Write path" {
  grid-columns: 2
  Ingress: "Ingress" {
    update1: "Person Attribute Updated"
    update2
  }
  indexes: @indexes.Condition
  Ingress.update1 -> indexes.real_time.data.0
  label.near: outside-top-center
  style.font-size: 40
}
