classes: {
  ...@index.classes
}
Updates: "Write path" {
  grid-columns: 2
  Events: "Updates" {
    grid-columns:1
    
    update1: "Person Attribute Updated"
  }
  indexes: @indexes.Condition
  Events.update1 -> indexes.control.Updates
  label.near: outside-top-center
  style.font-size: 30

}
